### ISSUE TITLE
d3 v4 support 

### ISSUE THREAD

**Issue by jashuRc** [Olical/lab#1]
This lab/js code is not working for d3 v4.
How to draw chart in react using d3 v4 ?

**Comment by Olical** [comment]
I can't really help you, I have never used d3 v4, the only way to get it working would be to go through every call d3 now makes to the DOM and make sure there's some sort of support for it in react-faux-dom. It was designed with d3 v3 in mind, either stick to that or avoid react-faux-dom I'm afraid.

**Comment by jashuRc** [comment]
Thank You for reply.
